-- MySQL Script generated by MySQL Workbench
-- seg 01 abr 2024 11:17:28
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
                                                 `idUsuario` INT NOT NULL AUTO_INCREMENT,
                                                 `tipoDeUsuario` ENUM('ADMINSTRADOR', 'PROFESSOR') NOT NULL,
    `login` VARCHAR(45) NOT NULL,
    `nomeCompleto` VARCHAR(200) NOT NULL,
    `senha` VARCHAR(200) CHARACTER SET 'armscii8' NOT NULL,
    `telefone` VARCHAR(45) COLLATE 'Default Collation' NOT NULL,
    `email` VARCHAR(100) NOT NULL,
    `ativo` TINYINT NOT NULL,
    PRIMARY KEY (`idUsuario`),
    UNIQUE INDEX `NomeUsuario_UNIQUE` (`login` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`disciplinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`disciplinas` (
                                                    `idDisciplina` INT NOT NULL,
                                                    `nomeDisciplina` VARCHAR(45) NOT NULL,
    `cargaHorario` INT NULL,
    PRIMARY KEY (`idDisciplina`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`turmas` (
                                               `idTurma` INT NOT NULL,
                                               `nome` VARCHAR(45) NOT NULL,
    `anoInicio` YEAR NOT NULL,
    `semestre` INT NOT NULL,
    `idDisciplina` INT NOT NULL,
    `idProfessor` INT NOT NULL,
    PRIMARY KEY (`idTurma`),
    INDEX `fk_turmas_disciplinas1_idx` (`idDisciplina` ASC) VISIBLE,
    INDEX `fk_turmas_usuarios1_idx` (`idProfessor` ASC) VISIBLE,
    CONSTRAINT `fk_turmas_disciplinas1`
    FOREIGN KEY (`idDisciplina`)
    REFERENCES `mydb`.`disciplinas` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_turmas_usuarios1`
    FOREIGN KEY (`idProfessor`)
    REFERENCES `mydb`.`usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ingredientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ingredientes` (
                                                     `idIngredientes` INT NOT NULL,
                                                     `nome` VARCHAR(45) NOT NULL,
    `unidadeDeMedida` VARCHAR(3) NOT NULL,
    `descricao` VARCHAR(200) NULL,
    `caminhoImagem` VARCHAR(200) NULL,
    PRIMARY KEY (`idIngredientes`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`requisicoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`requisicoes` (
                                                    `idRequisicao` INT NOT NULL,
                                                    `descricao` VARCHAR(200) NULL,
    `dataAula` DATE NOT NULL,
    `status` ENUM('PREENCHIMENTO', 'ENVIADO', 'APROVADO', 'REJEITADO', 'CORRECAO') NOT NULL,
    `idTurma` INT NOT NULL,
    `motivoDevolucao` VARCHAR(300) NULL,
    PRIMARY KEY (`idRequisicao`),
    INDEX `fk_requisicoes_turmas1_idx` (`idTurma` ASC) VISIBLE,
    CONSTRAINT `fk_requisicoes_turmas1`
    FOREIGN KEY (`idTurma`)
    REFERENCES `mydb`.`turmas` (`idTurma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`requisicoesIngedientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`requisicoesIngedientes` (
                                                               `idRequisicaoIngrediente` INT NOT NULL AUTO_INCREMENT,
                                                               `idRequisicao` INT NOT NULL,
                                                               `idIngrediente` INT NOT NULL,
                                                               `quantidade` INT NOT NULL,
                                                               INDEX `fk_requisicoes_has_ingredientes_ingredientes1_idx` (`idIngrediente` ASC) VISIBLE,
    INDEX `fk_requisicoes_has_ingredientes_requisicoes1_idx` (`idRequisicao` ASC) VISIBLE,
    PRIMARY KEY (`idRequisicaoIngrediente`),
    CONSTRAINT `fk_requisicoes_has_ingredientes_requisicoes1`
    FOREIGN KEY (`idRequisicao`)
    REFERENCES `mydb`.`requisicoes` (`idRequisicao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_requisicoes_has_ingredientes_ingredientes1`
    FOREIGN KEY (`idIngrediente`)
    REFERENCES `mydb`.`ingredientes` (`idIngredientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
